# This is a config for E2B sandbox template.
# You can use template ID (52a7btlnz08qi2cjrbom) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("52a7btlnz08qi2cjrbom") # Sync sandbox
# sandbox = await AsyncSandbox.create("52a7btlnz08qi2cjrbom") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('52a7btlnz08qi2cjrbom')

team_id = "5f90806b-dab0-4780-a0dd-4bebb07fccd9"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_id = "52a7btlnz08qi2cjrbom"
